[theme]
base="light"
primaryColor="#4a6fa5"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#000000"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
baseUrlPath = "/"

[browser]
serverAddress = "localhost"

[runner]
magicEnabled = false
fixMatplotlib = true

[client]
showErrorDetails = true

[ui]
hideTopBar = true

[global]
developmentMode = false
